apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "golang-consumer.name" . }}-{{ .Values.deployConfigs.namespace }}
  namespace: {{ .Values.deployConfigs.namespace }}
spec:
  scaleTargetRef:
    name: golang-consumer
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  maxReplicaCount: 5 # Optional. Default: 100
  minReplicaCount: 1 # Optional. Default: 0
  triggers:
    - type: rabbitmq
      metadata:
        host: {{ .Values.rabbitScalling.host }}
        protocol: auto
        queueName: {{ .Values.rabbitScalling.queueName }}
        value: "5"
        activationValue: "10.5"
        mode: QueueLength
